    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend><br>

        <div class="field customer_account">
            <label for="customer_account" class="label"><span><?php /* @escapeNotVerified */ echo __('Customer Account') ?></span></label>
            <div class="control">
                <input type="text" name="customer_account" id="customer_account" title="<?php /* @escapeNotVerified */ echo __('Customer Account') ?>" class="input-text" data-validate="{required:false}" autocomplete="off">
            </div>
        </div>
    </fieldset>
