<?php 
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div>
            <?php /* @escapeNotVerified */echo __('We can\'t find products matching the selection.') ?>
        </div>
    </div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode        = 'grid';
        $image           = 'category_page_grid';
        $showDescription = false;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode        = 'list';
        $image           = 'category_page_list';
        $showDescription = true;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
?>
<div class="products wrapper <?php /* @escapeNotVerified */echo $viewMode; ?> products-<?php /* @escapeNotVerified */echo $viewMode; ?>">
    <?php $iterator = 1;?>
    <ol class="products list items product-items">
        <?php /** @var $_product \Magento\Catalog\Model\Product */?>
        <?php foreach ($_productCollection as $_product): ?>
            <?php /* @escapeNotVerified */echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
            <div class="product-item-info" data-container="product-grid">
                <?php
                $productImage = $block->getImage($_product, $image);
                if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                    . 'top:' . $productImage->getHeight() . 'px;"';
                }
                $id            = $_product->getId();
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $obj_product   = $objectManager->create('Magento\Catalog\Model\Product');
                $product       = $obj_product->load($id);
                $productData   = $product->getPreLoadedTemplate();
                $isPdEnable    = $this->helper('Biztech\Productdesigner\Helper\Info')->isPdEnable($_product->getId());
                $config        = $objectManager->create('Magento\Framework\App\Config\ScopeConfigInterface');
                $layout        = $config->getValue('productdesigner/selectview/Selectview');
                if ($productData):
                    $designImages = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Designtemplateimages\Collection')->addFieldToFilter('designtemplates_id', array('eq' => $productData))->addFieldToFilter('design_image_type', 'base')->getFirstItem()->getData();
                $imagePath    = isset($designImages['image_path']) ? $designImages['image_path'] : '';
                ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php
                    echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)
                    ?>" class="product photo product-item-photo">
                    <?php // Product Image ?>
                                        <!--<a href="<?php /* @escapeNotVerified *///echo $_product->getProductUrl()     ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php //echo $productImage->toHtml(); ?>
                    </a>-->
                    <?php if ($imagePath): ?>
                        <span class="product-image-container" style="width:200px;">
                            <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                <img src="<?php
                                echo $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_page_image')->setImageFile($designImages['image_path'])->resize(200, 250)->keepAspectRatio(true)->constrainOnly(false)->getUrl();
                                ?>" alt="" />
                            </span>
                        </span>
                    <?php else: ?>
                        <?php echo $productImage->toHtml(); ?>
                    <?php endif;?>
                </a>
            <?php else: ?>
                <a href="<?php /* @escapeNotVerified */echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                    <?php echo $productImage->toHtml(); ?>
                </a>
            <?php endif;?>
            <div class="product details product-item-details">
                <?php
                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                ?>
                <strong class="product name product-item-name">
                    <?php if ($productData): ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php
                            echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)
                            ?>" class="product-item-link">
                            <?php
                            /* @escapeNotVerified */echo $_helper->productAttribute($_product, $_product->getName(), 'name');
//($_product, $_product->getEnableProductDesigner(), 'enable_product_designer');
                            ?>
                        </a>
                    <?php else: ?>
                        <a class="product-item-link"
                        href="<?php /* @escapeNotVerified */echo $_product->getProductUrl() ?>">
                        <?php /* @escapeNotVerified */echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                    </a>
                <?php endif;?>
            </strong>
            <?php if ($showDescription): ?>
                <div class="product description product-item-description">
                    <?php /* @escapeNotVerified */echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    <a href="<?php /* @escapeNotVerified */echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */echo $_productNameStripped ?>" class="action more">
                        <?php /* @escapeNotVerified */echo __('Learn More') ?>
                    </a>
                </div>
            <?php endif;?>
            <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $product       = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
            $tier_price    = $product->getPriceInfo()->getPrice('tier_price')->getTierPriceList();
            $cathelper     = $objectManager->create('Magento\Catalog\Helper\Data');
$priceHelper   = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
if (count($tier_price) > 0) {
    ?>
    <div id="tier-price-group">
        <ul class="prices-tier items">
            <div class="PriceBreakHeader">
                <div class="PriceBreakLine Column1">Qty</div>
                <div class="PriceBreakLine Column3">inc. VAT</div>
                <div class="PriceBreakLine Column2">exc. VAT</div>
            </div>
            <?php
            foreach ($tier_price as $price) {
                if ($price['isshow'] == "" || $price['isshow'] != 0) {
                    ?>
                    <li class="item">
                        <span class="tier-qty"><?php echo $price['price_qty']; ?></span>
                        <span class="tier-price">
                            <span class="price-container price-tier_price tax weee">
                                <span class="price-wrapper price-including-tax">
                                    <span class="price"><?php echo $priceHelper->currency($cathelper->getTaxPrice($product, $price['price']->getValue(), true, null, null, null, null, true, true), true, false); ?></span>
                                </span>
                                <span class="price-wrapper price-excluding-tax">
                                    <span class="price"><?php echo $priceHelper->currency($cathelper->getTaxPrice($product, $price['price']->getValue(), false, null, null, null, null, true, true), true, false); ?></span>
                                </span>
                            </span>
                        </span>
                    </li>
                    <?php
                }
            }
            ?>
        </ul>
    </div>
    <?php }?>
    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
    <div class="productlistright">
        <?php echo $block->getProductDetailsHtml($_product); ?>
        <?php /* @escapeNotVerified */echo $block->getProductPrice($_product) ?>
        <div class="pricing-unit"><span><?php /* @escapeNotVerified */echo $_helper->productAttribute($_product, $_product->getPricingUnit(), 'pricing_unit'); ?></span></div>
        <div class="product-item-inner">
            <div class="product actions product-item-actions" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                <div class="actions-primary" <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                    <?php if ($_product->isSaleable()): ?>
                        <?php $postParams = $block->getAddToCartPostParams($_product);?>
                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */echo $postParams['action']; ?>" method="post">
                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */echo $postParams['data']['product']; ?>">
                            <input type="hidden" name="<?php /* @escapeNotVerified */echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                            <?php echo $block->getBlockHtml('formkey') ?>
                            <?php
                            $stockItemRepository = $objectManager->create('Magento\CatalogInventory\Api\StockRegistryInterface');
                            $productStock        = $stockItemRepository->getStockItem($_product->getId());
                            ?>
                            <input type="hidden" id="miniqty<?php echo $_product->getId(); ?>" name="miniqty" value="<?php echo $productStock->getMinSaleQty(); ?>">
                            <?php if (!$isPdEnable) {?>
                            <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                                <span><?php /* @escapeNotVerified */echo __('Add to Cart') ?></span>
                            </button>
                            <?php }?>
                        </form>
                        <?php
                        $id            = $_product->getId();
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $obj_product   = $objectManager->create('Magento\Catalog\Model\Product');
                        $product       = $obj_product->load($id);
                        $config        = $objectManager->create('Magento\Framework\App\Config\ScopeConfigInterface');
                        $layout        = $config->getValue('productdesigner/selectview/Selectview');
                        $band_enable   = $product->getEnableWristband();
                        $product->getResource()->getAttribute('media_gallery')
                        ->getBackend()->afterLoad($product);
                        $product_images = $product->getMediaGalleryImages();
                        $productData    = $product->getPreLoadedTemplate();
                        ?>
                        <?php $isPdEnable = $this->helper('Biztech\Productdesigner\Helper\Info')->isPdEnable($_product->getId());?>
                        <?php if ($this->helper('Biztech\Productdesigner\Helper\Data')->isEnable()): ?>
                            <?php if (isset($isPdEnable) && $isPdEnable && count($product_images) > 0): ?>
                                <?php if ($this->helper('Biztech\Productdesigner\Helper\Info')->checkDesignArea($_product->getId())) {
                                    ?>
                                    <?php if ($productData) {?>
                                    <?php if ($band_enable) {?>
                                    <button type="button" title="<?php echo __('Design It') ?>" class="button btn-cart list-design-button" onclick="window.location.href = '<?php echo $this->getUrl('productdesigner/index/band', array('_secure' => $this->getRequest()->isSecure())) . 'id/' . $_product->getId() . 'templateid/' . $productData; ?>'"><span><span><?php echo __('Design It') ?></span></span>
                                    </button>
                                    <?php } else {?>
                                    <button type="button" title="<?php echo __('Design It') ?>" class="button btn-cart list-design-button" onclick="<?php if ($layout == 'box_view'): ?>window.location.href = '<?php
                                        echo $this->getUrl('productdesigner/index/index', array('_secure' => $this->getRequest()->isSecure())) . 'id/' . $_product->getId() . '/templateid/' . $productData;
                                        ?>' <?php else: ?>window.location.href = '<?php
                                        echo $this->getUrl('productdesigner/index/full', array('_secure' => $this->getRequest()->isSecure())) . 'id/' . $_product->getId() . '/templateid/' . $productData;
                                        ?>'<?php endif;?>"><span><span><?php echo __('Design It') ?></span></span>
                                    </button>
                                    <?php }?>
                                    <?php } else {
                                        ?>
                                        <?php if ($band_enable) {?>
                                        <button type="button" title="<?php echo __('Design It') ?>" class="button btn-cart list-design-button" onclick="window.location.href = '<?php echo $this->getUrl('productdesigner/index/band', array('_secure' => $this->getRequest()->isSecure())) . 'id/' . $_product->getId(); ?>'"><span><span><?php echo __('Design It') ?></span></span>
                                        </button>
                                        <?php } else {?>
                                        <button type="button" title="<?php echo __('Design It') ?>" class="button btn-cart list-design-button" onclick="<?php if ($layout == 'box_view'): ?>window.location.href = '<?php
                                            echo $this->getUrl('productdesigner/index/index', array('_secure' => $this->getRequest()->isSecure())) . 'id/' . $_product->getId();
                                            ?>' <?php else: ?>window.location.href = '<?php
                                            echo $this->getUrl('productdesigner/index/full', array('_secure' => $this->getRequest()->isSecure())) . 'id/' . $_product->getId();
                                            ?>'<?php endif;?>"><span><span><?php echo __('Design It') ?></span></span>
                                        </button>
                                        <?php }?>
                                        <?php }?>
                                        <?php }?>
                                    <?php endif;?>
                                <?php endif;?>
                            <?php else: ?>
                                <?php if ($_product->getIsSalable()): ?>
                                    <div class="stock available"><span><?php /* @escapeNotVerified */echo __('In stock') ?></span></div>
                                <?php else: ?>
                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */echo __('Out of stock') ?></span></div>
                                <?php endif;?>
                            <?php endif;?>
                        </div>
                        <div data-role="add-to-links" class="actions-secondary" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                            <?php endif;?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
    <?php endforeach;?>
</ol>
</div>
<?php echo $block->getToolbarHtml() ?>
<?php if (!$block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
        { "[data-role=tocart-form], .form.map.checkout": { "catalogAddToCart": {} } }
    </script>
<?php endif;?>
<?php endif;?>