<?php
$category_id = $this->getCatId();
$image = 'category_page_list';
if ($category_id == null) {
    //$category_id = $block->getProductDefaultCategory();
}
?>

<?php if ($category_id) : ?>
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

    $obj_product = $objectManager->create('Magento\Catalog\Model\Category');
    $category = $obj_product->load($category_id);


    $products = $category->getProductCollection();

    $products->addAttributeToSelect('*')->addAttributeToFilter('visibility', array("neq" => 1));
    $products->addAttributeToFilter('status', array("eq" => 1));
    $products->addAttributeToFilter('type_id', array("in" => array('simple', 'configurable')));
    $products->addAttributeToFilter('enable_product_designer', array("eq" => 1));

    $layout = $block->getView();

    //Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($products);  
    ?>

    <ul id="product_list" class="product_list">
        <?php
        $is_product = 0;
        foreach ($products as $_product):
            $product_type = $_product->getTypeId();
            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
            //$designs = $this->helper('Biztech\Productdesigner\Helper\Info')->getProductInfo($_product->getId());
            //$default_color = $this->helper('Biztech\Productdesigner\Helper\Info')->getDefaultImage($_product->getId()) ? $this->helper('Biztech\Productdesigner\Helper\Info')->getDefaultImage($_product->getId()) : 0;
            //$decodedDesigns = json_decode($designs);
            if ($product_type != 'configurable') {
                //if (sizeof($decodedDesigns->images[$default_color])) :
                $is_product = 1;

                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $obj_product = $objectManager->create('Magento\Catalog\Model\Product');
                $product_data = $obj_product->load($_product->getId());

                $productImage = $_imagehelper->init($_product, $image)->resize(100)->getUrl();
                ?>
                <li>
                    <a href="<?php echo $this->getUrl('productdesigner') . '?id=' . $_product->getId(); ?>"><img src="<?php echo $productImage; ?>" alt="<?php echo $product_data->getName(); ?>"  title="<?php echo $product_data->getName(); ?>" data-product_id="<?php echo $_product->getId(); ?>" class="product-image">
                    </a><p><?php echo $product_data->getName(); ?></p>
                </li>
                <?php //endif;  ?>
                <?php
            } else {
                //if (sizeof($decodedDesigns->images->$default_color)) :
                $is_product = 1;
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $obj_product = $objectManager->create('Magento\Catalog\Model\Product');
                $product_data = $obj_product->load($_product->getId());
                //$product_image = $_imagehelper->init($_product, 'thumbnail')->resize(100);
                $productImage = $_imagehelper->init($_product, $image)->resize(200)->getUrl();
                ?>
                <li>
                    <a href="<?php if ($layout == 'box_view'): ?><?php echo $this->getUrl('productdesigner') . '?id=' . $_product->getId(); ?><?php else: ?><?php echo $this->getUrl('productdesigner/index/full') . '?id=' . $_product->getId(); ?><?php endif; ?>">
                        <img src="<?php echo $productImage; ?>" alt="<?php echo $product_data->getName(); ?>"  title="<?php echo $product_data->getName(); ?>" data-product_id="<?php echo $_product->getId(); ?>" class="product-image">
                    </a>
                    <p><a href="<?php if ($layout == 'box_view'): ?><?php echo $this->getUrl('productdesigner') . '?id=' . $_product->getId(); ?><?php else: ?><?php echo $this->getUrl('productdesigner/index/full') . '?id=' . $_product->getId(); ?><?php endif; ?>"><?php echo $product_data->getName(); ?></a></p>
                </li>
                <?php //endif;  ?>
                <?php
            }
        endforeach;
        ?>
        <?php if (count($products) == 0 || !$is_product): ?>
            <li class="note-message"> <span class="a-center"> <?php echo __("Sorry, no products found."); ?> </span> </li>
            <?php endif; ?>        
    </ul>
<?php endif; ?>
    