<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_AddMultipleProducts
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php 
$helper = $this->helper('Bss\AddMultipleProducts\Helper\Data');
$isEnable = $helper->isEnabled();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$class_apply = $helper->displayAddmunltiple();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$group_Id = 0;
if ($customerSession->isLoggedIn()) {
	$group_Id = $customerSession->getCustomer()->getGroupId();
}
?>
<?php if ($isEnable) : ?>
<?php if ( is_array($helper->getCustomerGroup()) && (in_array(32000,$helper->getCustomerGroup()) || in_array($group_Id,$helper->getCustomerGroup())) ): ?>
<div id="bss_ajaxmuntiple_cart_popup"></div>
<script>
    require(['jquery'], function ($) {
        $(document).ready(function(){
            var class_apply = '<?php echo $class_apply ?>';
            var showcheckboxproduct = '<?php echo $helper->showSelectProduct();?>';
            var showtotal = '<?php echo $helper->showTotal();?>';
            var showstick = '<?php echo $helper->showStick();?>';
            _init(class_apply,showcheckboxproduct,showtotal);
            // show total qty or item when input change
            $('.qty-m-c').on('input',function(e){
                var total_qty = 0;
                var total_product = 0;
                if ($(this).parents('.'+ $(this).data('group')).length) {

                    $(this).parents('.'+ $(this).data('group')).find('.qty-m-c').each(function(){
                        if($(this).parents('.add-option').length === 0){
                            if ($(this).val() && $(this).val() > 0) {
                                    if (showcheckboxproduct) {
                                        if($(this).siblings('input[name="product-select[]"]').is(':checked')){
                                            total_qty += parseInt($(this).val());
                                            total_product += 1;
                                            if (showstick) {
                                                $(this).parents('.product-item').css('position','relative');
                                                $(this).parents('.product-item').prepend('<div class="ad-mt-stick"></div>');
                                            }
                                        }else{
                                            $(this).parents('.product-item').css('position','');
                                            $(this).parents('.product-item').find('.ad-mt-stick').remove();
                                        }
                                    }else{
                                        total_qty += parseInt($(this).val());
                                        total_product += 1;
                                        if (showstick) {
                                            $(this).parents('.product-item').css('position','relative');
                                            $(this).parents('.product-item').prepend('<div class="ad-mt-stick"></div>');
                                        }
                                    }
                                
                            }else{
                                $(this).parents('.product-item').css('position','');
                                $(this).parents('.product-item').find('.ad-mt-stick').remove();
                            }
                        }
                    })
                    bt = $(this).data('group').split('-');
                    if (showtotal == 2) {
                        $('.button-bs-ad button#bt-ad-mt-'+ bt[3] +' .total_qty span').text( total_qty );
                    }
                    if (showtotal == 1) {
                        $('.button-bs-ad button#bt-ad-mt-'+ bt[3] +' .total_products span').text( total_product );
                    }
                }     
            });
            // show  total qty or items after load
            setTimeout(function(){
                $('.addmanytocart').each(function(){
                    var total_qty1 = 0;
                    var total_product1 = 0;
                    gr = $(this).attr('id').split('-');
                    if ($('.gr-add-mt-'+ gr[3]).length) {

                        $('.gr-add-mt-'+ gr[3]).find('.qty-m-c').each(function(){
                            if($(this).parents('.add-option').length === 0){
                                if ($(this).val() && $(this).val() > 0) {
                                    if (showcheckboxproduct) {
                                        if($(this).siblings('input[name="product-select[]"]').is(':checked')){
                                            total_qty1 += parseInt($(this).val());
                                            total_product1 += 1;
                                        }
                                    }else{
                                        total_qty1 += parseInt($(this).val());
                                        total_product1 += 1;
                                    }
                                }else{

                                }
                            }
                        })
                        if (showtotal == 2) {
                            $(this).find('.total_qty span').text( total_qty1 );
                        }
                        if (showtotal == 1) {
                            $(this).find('.total_products span').text( total_product1 );
                        }
                    }
                })
            })
            // click select all
             $('.add-all-product').on('click',function(){

                select = $(this).parents('.button-bs-ad').find('button').attr('id').split('-');
                form = $('#add-muntiple-product-trim'+select[3]);
                 if($(this).is(':checked')) {
                    $('.add-all-product').prop( "checked", true );
                    $('.add-mt-' + select[3] ).each(function(){
                        // $(this).prop('checked', true);
                        if (!$(this).is(':checked')) {
                            $(this).trigger('click');
                        }
                        addOptions(form,$(this).val());
                    })
                 }else{
                    $('.add-all-product').prop( "checked", false );
                    $('.add-mt-' + select[3] ).each(function(){
                        // $(this).prop('checked', false);
                        if ($(this).is(':checked')) {
                            $(this).trigger('click');
                        }
                        $(form).find('.vls_' + $(this).val()).remove();
                    })
                 }
             })
             if (!showcheckboxproduct) {
                setTimeout(function(){
                 $('input[name="product-select[]"]').each(function(){
                        var form = $('#add-muntiple-product-'+$(this).data('froma'));
                        addOptions(form,$(this).val());
                    })
                },0)
             }
             // click selected
             $('.product-select').on('click',function(){
                var total_qty2 = 0;
                var total_product2 = 0;
                var product_id = $(this).val();
                var form = $('#add-muntiple-product-'+$(this).data('froma'));
                 if($(this).is(':checked')) {
                    addOptions(form,product_id);
                    if (showstick) {
                        if($(this).siblings('.qty-m-c').val() > 0 ){
                            $(this).parents('.product-item').css('position','relative');
                            $(this).parents('.product-item').prepend('<div class="ad-mt-stick"></div>');
                        }else{
                            $(this).parents('.product-item').css('position','');
                            $(this).parents('.product-item').find('.ad-mt-stick').remove();
                        }
                    }
                 }else{

                    $(form).find('.vls_' + product_id).remove();
                    $(this).parents('.product-item').css('position','');
                    $(this).parents('.product-item').find('.ad-mt-stick').remove();
                 }
                _select =  $(this).siblings('.qty-m-c').data('group').split('-');
                // gr1 = $(this).attr('id').split('-');
                    if ($('.gr-add-mt-'+ _select[3]).length) {

                        $('.gr-add-mt-'+ _select[3]).find('.qty-m-c').each(function(){
                            if($(this).parents('.add-option').length === 0){
                                if ($(this).val() && $(this).val() > 0) {
                                    if (showcheckboxproduct) {
                                        if($(this).siblings('input[name="product-select[]"]').is(':checked')){
                                            total_qty2 += parseInt($(this).val());
                                            total_product2 += 1;
                                        }
                                    }else{
                                        total_qty2 += parseInt($(this).val());
                                        total_product2 += 1;
                                    }
                                }else{

                                }
                            }
                        })
                        if (showtotal == 2) {
                            $('.button-bs-ad button#bt-ad-mt-'+ _select[3] +' .total_qty span').text( total_qty2 );
                        }
                        if (showtotal == 1) {
                            $('.button-bs-ad button#bt-ad-mt-'+ _select[3] +' .total_products span').text( total_product2 );
                        }
                    }
             })
            
            selectOptions();
            if (showstick) {
                setTimeout(function(){
                 $('input[name="product-select[]"]').each(function(){
                       if (showcheckboxproduct ) {
                            if($(this).siblings('input[name="product-select[]"]').is(':checked') && $(this).val() > 0){
                                $(this).parents('.product-item').css('position','relative');
                                $(this).parents('.product-item').prepend('<div class="ad-mt-stick"></div>');
                                total_qty += parseInt($(this).val());
                                total_product += 1;
                            }
                        }else{
                            if ($(this).val() > 0) {
                                $(this).parents('.product-item').css('position','relative');
                                $(this).parents('.product-item').prepend('<div class="ad-mt-stick"></div>');
                            }
                        }
                    })
                },0)
            }

            // $(window).load(function(){
            // if ($(window).width() > 768) {
                // setTimeout(function(){
                    jQuery(".addmanytocart.left-scroll").css({
                            position: 'absolute',
                            top: '0px',
                            zIndex:'999',
                            right: '0px'
                    });
                // },200)
            // }
            
            timeout = null;
            var target = '';
            if($(".addmanytocart.left-scroll").length){
                 target = $(".addmanytocart.left-scroll").offset().top;
            }
            // console.log(target);
            $(window).scroll(function () {
                // if (!timeout) {
                    // timeout = setTimeout(function () {            
                        // clearTimeout(timeout);
                        // timeout = null;
                        // if ($(window).width() > 768) {
                            if ($(".addmanytocart.left-scroll").length) {
                                if ($(window).scrollTop() >= target ) {
                                    $(".addmanytocart.left-scroll").css({
                                            position: 'absolute',
                                            top: $(window).scrollTop()  + 15 - target + 'px',
                                            right: '0px'
                                    });
                                }
                                else{
                                    $(".addmanytocart.left-scroll").css({
                                            position: 'absolute',
                                            top: '0px',
                                            zIndex:'999',
                                            right: '0px'
                                    });
                                }
                            }
                        // }
                    // }, 0);
                // }
            });
        // });
        });
            
        function _init(class_apply,showcheckboxproduct,showtotal){
            var trainindIdArray = class_apply.split(',');
            var form_addmuntiple = '';
            var url_addmuntiple = "<?php echo $storeManager->getStore()->getBaseUrl().'addmuntiple/cart/addMuntiple' ?>";
            var productidad = '';
            var checkall = '';
            var total_init = '';
            var positionbutton = <?php echo $helper->positionButton() ?>;
            $.each(trainindIdArray, function(index, value) { 
               
                if ($(value).length) {
                    //add checkbox all
                    $(value).each(function(i){
                        form_addmuntiple = '<form action="'+ url_addmuntiple + '" method="post"  id="add-muntiple-product-trim'+ i +'" class="add-mt-'+ i +'"><div class="add-option" style="display: none;"></div></form>';
                        if (showcheckboxproduct) {
                          checkall =  '<input type="checkbox" name="addall" class="add-all-product" value=""><label for="checkall" style="margin-right: 15px;"><?php echo __('Check All') ?></label>';
                        }
                        if (showtotal == 1) {
                            total_init = '<span class="total_products">(<?php echo __('Total Products') ?>: <span>0</span>)</span>';
                        }
                        if (showtotal == 2) {
                            total_init = '<span class="total_qty">(<?php echo __('Total Qty') ?>: <span>0</span>)</span>';
                        }
                         // add form and  button add all 
                        if( $(this).find('.actions-primary').length ){
                            var button = '<div  class="button-bs-ad"> ' + checkall + '<button type="button" title="<?php echo $helper->getTextbuttonaddmt() ;?>" id="bt-ad-mt-'+ i +'" data-froma="trim'+ i + '" class="action addmanytocart primary"><span><?php echo $helper->getTextbuttonaddmt() ;?></span>'+ total_init +'</button></div>';
                            $(this).css('position','relative');
                            $(this).addClass('gr-add-mt-'+ i);
                             // add form 
                            $(this).append(form_addmuntiple);
                            // add button
                            if (positionbutton === 0) {
                                $(this).prepend(button);
                            }
                            if (positionbutton === 1) {
                                $(this).append(button);
                            }
                            if (positionbutton === 2) {
                                $(this).prepend(button);
                                $(this).append(button);
                            }
                            if (positionbutton === 3) {
                                $(this).append(button).find('.addmanytocart').addClass('left-scroll');
                            }
                        }
                   
                        // add box qty and check box
                        if ( $(this).find('.actions-primary form').length ) {
                           $(this).find('.actions-primary form').each(function(){    
                                if ( $(this).find('input[name="product"]').length ) {
                                            productidad = $(this).find('input[name="product"]').val();
                                }else{
                                    if ($(this).parents('.product.info').find('.price-box').data('product-id')!='') {
                                            productidad = $(this).parents('.product.info').find('.price-box').data('product-id');
                                    }
                                }
                                if (productidad != '') {
                                    if (showcheckboxproduct) {
                                        $(this).find('button.tocart').before('<input type="checkbox" name="product-select[]" id="product_'+productidad +'" data-froma="trim'+ i + '" class="product-select add-mt-'+ i +'" value="'+ productidad +'">');
                                    }else{
                                        $(this).find('button.tocart').before('<input type="hidden" name="product-select[]" id="product_'+productidad +'" data-froma="trim'+ i + '" class="add-mt-'+ i +'" value="'+ productidad +'">');
                                    }
									var minsalqt = $("#miniqty"+ productidad).val();
                                $(this).find('button.tocart').before('<input type="text" class="qty-m-c" data-group="gr-add-mt-'+ i +'" name="qty" placeholder="0" value="'+minsalqt+'">');
                                }
                            })
                            
                        }else{
                            $(this).find('li.product-item .actions-primary').each(function(){
                                var dataPost = jQuery.parseJSON($(this).find('.action.tocart').attr('data-post'));
                                if (dataPost) {
                                    if (dataPost.data.product) {
                                        productidad = dataPost.data.product;
                                    }else{
                                        if ($(this).parents('li.product-item').find('.price-box').data('product-id')!='') {
                                            productidad = $(this).parents('li.product-item').find('.price-box').data('product-id');
                                        }
                                    }
                                }
                                if (!dataPost && $(this).parents('li.product-item').find('.price-box').data('product-id')!='') {
                                    productidad = $(this).parents('li.product-item').find('.price-box').data('product-id');
                                }
                                if (productidad != '') {
                                    if (showcheckboxproduct) {
                                        $(this).find('button.tocart').before('<input type="checkbox" name="product-select[]" id="product_'+ productidad +'" class="product-select add-mt-'+ i +'"  data-froma="trim'+ i + '" value="'+ productidad +'">');
                                    }else{
                                        $(this).find('button.tocart').before('<input type="hidden" name="product-select[]" id="product_'+ productidad +'" class="add-mt-'+ i +'"  data-froma="trim'+ i + '" value="'+ productidad +'">'); 
                                    }
									var minsalqt = $("#miniqty"+ productidad).val();
                                    $(this).find('button.tocart').before('<input type="text" class="qty-m-c" data-group="gr-add-mt-'+ i +'" name="qty" placeholder="0" value="'+minsalqt+'">');
                                }
                            })
                        }
                    })
                }
            });
        }
        function addOptions(form,product_id){
            $('#product_' + product_id).parents('.actions-primary').find('input').each(function(){
                    if ($(this).attr('name') !='uenc' && $(this).attr('name') !='form_key' && $(this).attr('name') !='product') {
                        var name = product_id + '_' + $(this).attr('name');
                        if ( $(this).attr('name') == 'product-select[]'  && ($(form).find('#product_' + product_id).length == 0 || $(this).parents('.wishlist').length ) ) {
                                $(this).clone().prependTo( $( form ).find(".add-option" ) ).addClass('vls_' + product_id).val($(this).val());
                        }
                        else{ 
                            if($(form).find('input[name="'+ name +'"]').length == 0) {
                                $(this).clone().prependTo( $( form ).find(".add-option" ) ).addClass('vls_' + product_id).attr('name',name).val($(this).val());
                            }
                        }
                    }
            })
            $('#product_' + product_id).parents('.actions-primary').find('textarea').each(function(){
                var name = product_id + '_' + $(this).attr('name');
                if ( $(form).find('textarea[name="'+ name +'"]').length == 0) {
                        $(this).clone().prependTo( $( form ).find(".add-option" ) ).addClass('vls_' + product_id).attr('name',name).val($(this).val());
                }
            })
            $('#product_' + product_id).parents('.actions-primary').find('select').each(function(){
                var name = product_id + '_' + $(this).attr('name');
                if ( !$(form).find('select[name="'+ name +'"]').length == 0) {
                    $(this).clone().prependTo( $( form ).find(".add-option" ) ).addClass('vls_' + product_id).attr('name',name).val($(this).val());
                }
            })
        }

        function selectOptions(){
            $('.product-item-actions input,.product-item-actions select , .product-item-actions textarea').bind("change paste keyup", function(){
                var product_id = $(this).parents('.actions-primary').find('input[name="product-select[]"]').val();
                var form = $('#add-muntiple-product-'+$(this).parents('.actions-primary').find('input[name="product-select[]"]').data('froma'));
                var name = product_id + '_' + $(this).attr('name');
                if ($(this).is("input")) {
                    $( form ).find(".add-option" ).find('input[name="'+ name +'"]').val($(this).val());
                }
                if ($(this).is("select")) {
                    $( form ).find(".add-option" ).find('select[name="'+ name +'"]').val($(this).val());
                }
                if ($(this).is("textarea")) {
                    $( form ).find(".add-option" ).find('textarea[name="'+ name +'"]').val($(this).val());
                }
            });
        }
    });

	var ajaxCart;
	require(['jquery', 'Bss_AddMultipleProducts/js/ajax', 'Bss_AddMultipleProducts/js/jquery.fancybox.min'],function($){
		$(document).ready(function() {
			ajaxCart = new BssAjaxCart();
			ajaxCart.init('<?php  echo $storeManager->getStore()->getBaseUrl().'addmuntiple/cart/'; ?>');
		});
		
	});
</script>
<?php endif ?>
<?php endif ?>