<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_AddMultipleProducts
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
	$helper = $this->helper('Bss\AddMultipleProducts\Helper\Data');
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$btnTextColor = $helper->getBtnTextColor();
	$btnContinueBackground = $helper->getBtnContinueBackground();
	$btnContinueHover = $helper->getBtnContinueHover();
	$btnViewcartBackground = $helper->getBtnViewcartBackground();
	$btnViewcartHover = $helper->getBtnViewcartHover();
	$url_media = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	if ($helper->backGroundStick()!='') {
		$url_stick = $url_media.'addmunltipleproduct/stick/'.$helper->backGroundStick();
	}else{
		$url_stick = $url_media.'addmunltipleproduct/stick/default/stick.png';
	}
	
?>
<style>
	#bss_ajaxmuntiple_cart_popup .btn-continue .continue {
		background: #<?php echo $btnContinueBackground; ?>;
		color: #<?php echo $btnTextColor; ?>;
	}

	#bss_ajaxmuntiple_cart_popup .btn-continue .continue:hover {
	    background: #<?php echo $btnContinueHover; ?>;
	}

	#bss_ajaxmuntiple_cart_popup .btn-viewcart .viewcart {
	    background: #<?php echo $btnViewcartBackground; ?>;
	    color: #<?php echo $btnTextColor; ?>;
	}

	#bss_ajaxmuntiple_cart_popup .btn-viewcart .viewcart:hover {
	    background: #<?php echo $btnViewcartHover; ?>;
	}
	.ad-mt-stick{
		background: url(<?php echo $url_stick; ?>);
		display: block;
	    height: 30px;
	    width: 30px;
	    z-index: 4;
	    background-size: 30px;
	    background-repeat: no-repeat;
	    position: absolute;
	    right: 15px;
	    top: 5px;
	}
	.list .ad-mt-stick{
		left: 15px;
	}
</style>