<?php
$cat_id = $this->getCatId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$obj_product = $objectManager->create('Biztech\Productdesigner\Model\Producttemplate');
if (!$cat_id) {
    $cat_id = $block->getDefaultTempalateCategory();
    $product_id = $this->getRequest()->getParam('id');
    
    
    $template_obj = $obj_product->load($product_id,
            'product_id');

    $templates = explode(',',
            $template_obj->getTemplates());
    if (!in_array($cat_id,
                    $templates)) {

        /* $designs = Mage::getModel('productdesigner/designtemplatescategory')->load($templates[0])->getDesigns();
          $designs_col = explode(',', $designs); */
        $designs_col = array();
    } else {
        $obj_product = $objectManager->create('Biztech\Productdesigner\Model\Designtemplatecategory');
        $designs = $obj_product->load($cat_id)->getDesigns();
        $designs_col = explode(',',
                $designs);
    }
} else {
    $designs = $objectManager->create('Biztech\Productdesigner\Model\Designtemplatecategory');
    $templateModel = $designs->load($cat_id)->getDesigns();
    $designs_col = explode(',',
            $templateModel);
}

?>

<ul id="template_list" class="product_list">

    <?php if (isset($designs)): ?>

        <?php
        foreach ($designs_col as $d):
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $obj_product = $objectManager->create('Biztech\Productdesigner\Model\Designtemplates');
            $design_obj = $obj_product->load($d);
            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
            // $design_obj = Mage::getModel('productdesigner/designtemplates')->load($d);
            $product_id = $design_obj->getProductId();

            if ($product_id != null):
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $obj_product = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Designtemplateimages\Collection')->addFieldToFilter('designtemplates_id',
                                Array('eq' => $d))->addFieldToFilter('design_image_type',
                        'base');
                $designImages = $obj_product->getData();
                //$designImages = Mage::getModel('productdesigner/designtemplatesimages')->getCollection()->addFieldToFilter('designtemplates_id', Array('eq' => $d))->addFieldToFilter('design_image_type', 'base')->getFirstItem()->getData();
                
                $obj_product = $objectManager->create('Magento\Catalog\Model\Product');
                $product = $obj_product->load($product_id);
                //$product = Mage::getModel('catalog/product')->load($product_id);
                $url = $_imagehelper->init($product,
                                'product_page_image_small')->setImageFile($designImages[0]['image_path'])->resize(135)->getUrl();
                ?>
                <li>
                    <img class="product-image design" width="50" height="50" alt="" design-id="<?php echo $d; ?>" src="<?php echo $url; ?>">
                </li>
                <?php
            endif;
        endforeach;
        ?>
    <?php else: ?>
        <li class="note-message"> <span class="a-center"> <?php echo __("Sorry, no designs found."); ?></span></li>
        <?php endif; ?>    
</ul>