<?php if($menu = $this->getMenu()){ ?>
<?php
$data = $this->helper("\Ves\Megamenu\Helper\Data");
$html = $class = '';
$mobileTemplate = $menu->getData("mobile_template");
if(!$mobileTemplate) $mobileTemplate = 1;
if($this->hasData("mobile_template")) $mobileTemplate = $this->getData("mobile_template");
if($mobileTemplate == 0){
	$class = 'offcanvas-menu offcanvas-menu-left ves-megamenu-mobile';
}elseif($mobileTemplate == 3){
	$class = 'ves-drill-down-menu';	
}else{
	$class = 'ves-megamenu-mobile';
}
if($mobileTemplate == 2 && $menu->getMobileMenuAlias() && $this->getMobileDetect()->isMobile()){
	$html = $block->getMobileTemplateHtml($menu->getMobileMenuAlias());
} else {
	$menuItems = $menu->getData('menuItems');
	$structure = json_decode($menu->getStructure(), true);
	if(is_array($structure)){
		foreach ($structure as $k => $v) {
			$itemData = $data->renderMenuItemData($v, [], $menuItems);
			$html .= $data->drawItem($itemData);
		}
	}
}
$html = $data->filter($html);

$alias = $menu->getAlias().time().rand();
$disableBellow = (int)$menu->getData('disable_bellow');

$desktopTemplate = $menu->getData("desktop_template");
if(!$desktopTemplate) $desktopTemplate = 'horizontal';
if($this->hasData("desktop_template")) $desktopTemplate = $this->getData("desktop_template");

$event = $menu->getData("event");
if(!$event) $event = 'hover';
if($this->hasData("event")) $event = $this->getData("event");

$class .= ' ' . $menu->getData("classes");

?>
<div class="block ves-menu <?php echo $class ?>" id="<?php echo $alias ?>-menu">
	<?php if($title = $this->getData("title")){ ?>
	<div class="block-title"><strong><span><?php echo __($title); ?></span></strong></div>
	<?php } ?>
	<nav class="navigation" role="navigation">
		<ul id="<?php echo $alias ?>" class="ves-megamenu <?php echo 'menu-' . $event ?> ves-<?php echo $desktopTemplate ?>" <?php if($disableBellow>0){ ?>data-disable-bellow="<?php echo $disableBellow ?>"<?php } ?>>
			<?php echo $html; ?>
		</ul>
	</nav>
	<?php if($html!=''){ ?>
	<script type="text/javascript">
		require(['jquery',
			<?php if($menu->getData('scrolltofixed')){ ?>'scrolltofixed'<?php } ?>
			],function($){
				jQuery(document).ready(function($) {
					<?php if ($mobileTemplate == 3) { ?>
						$('.ves-drill-down-menu').find('.opener').addClass('ves-click');
						$(window).on('load resize',function(e){
							e.preventDefault();

							var back        	= '<div class="hide-submenu"></div>';
							var subHide     	= $(back);
							var subMenu       	= $('.ves-drill-down-menu .submenu');
							
							// Add submenu hide bar
							if (subHide.children('hide-submenu').length ==0) {
								subHide.prependTo(subMenu);
							}
							var subHideToggle 	= $('.ves-drill-down-menu .hide-submenu');
							// Hide submenu
							subHideToggle.on("click", function() {
								$(this).parent().parent().parent().removeClass('view-submenu');
								$(this).parent().parent().parent().parent().parent().parent().parent().parent().removeClass('view-submenu');
								$(this).parent().hide();
							});

							if ($(window).width() <= 768){
								
								$('.ves-drill-down-menu').find('.opener').addClass('fa fa-arrow-right').removeClass('opener');
								$('.ves-drill-down-menu').find('.navigation').addClass('navdrilldown').removeClass('navigation');
								$('.ves-drill-down-menu #<?php echo $alias ?> .ves-click').on('click', function(e) {
									e.preventDefault();
									if ($(window).width() <= 768){	
										
										$(this).removeClass('.item-active');
										$(this).parents('.submenu').addClass('view-submenu');
										$(this).parents('ul.ves-megamenu').addClass('view-submenu');
										var a = $(this).parents('li.nav-item').offset().top;
										var b = $(this).parents('ul.ves-megamenu').offset().top;
										var c = $(this).parent().parent().offset().top;

										$(this).parents('li.nav-item').children('.submenu').css('top',b-a+'px');
										$(this).parent().parent().children('.submenu').css('top',b-c+'px');
										$('.submenu.dropdown-menu').hide();
										$(this).parents('.submenu').show();
										$(this).parent().parent().children('.submenu').show();
										return false;

									}	
								});
							}else {
								
								$('.ves-drill-down-menu').find('.fa-arrow-right').addClass('opener').removeClass('fa fa-arrow-right');
								$('.ves-drill-down-menu').find('.navdrilldown').addClass('navigation').removeClass('navdrilldown');
							}
						});
						<?php } ?>	
						jQuery('#<?php echo $alias ?>-menu .ves-megamenu .level0').hover(function() {
							var mParent = jQuery(this).parents('.ves-megamenu').offset().top;
							var mHeight = jQuery(this).offset().top;
							var mTop    = (mHeight - mParent) + jQuery(this).height();
							jQuery(this).find('.submenu').first().css({top:mTop+"px"});
						});
						<?php if($menu->getData('scrolltofixed')){ ?>

							$('.nav-sections-items > .nav-sections-item-content').scrollToFixed({
								zIndex: 99
							});

							$(window).on("resize load", function(){
								if ($(window).width() < 768){
									$('.nav-sections-items > .nav-sections-item-content').css({position: '', top: '', width: '100%'});
								}
							});
							var menuParentPosition = $('#<?php echo $alias ?>-menu').parents('.sections.nav-sections').offset().top;
							$(window).scroll(function() {
								var height = $(window).scrollTop();
								if (height<(menuParentPosition) - $('#<?php echo $alias ?>-menu').height()) {
									$('.nav-sections-items > .nav-sections-item-content').css({position: '', top: '', width: '100%'});
								}
								$('.section-items.nav-sections-items').find('div').each(function(index, el) {
									if ($(this).html() == '' && $(this).attr('class')=='') {
										$(this).remove();
									}
								});
							});
							<?php } ?>
							jQuery('p').each(function() {
								var $this = $(this);
								if ($this.html().replace(/\s|&nbsp;/g, '').length == 0)
								$this.remove();
							});
						});
				var menuToogle = function () {
					if ($('html').hasClass('nav-open')) {
						$('html').removeClass('nav-open');
						setTimeout(function () {
							$('html').removeClass('nav-before-open');
						}, 300);
					} else {
						$('html').addClass('nav-before-open');
						setTimeout(function () {
							$('html').addClass('nav-open');
						}, 42);
					}
				}
				$(document).on("click", ".action.nav-toggle", menuToogle);

				$(document).on("click", ".ves-overlay<?php echo $alias ?>", function(){
					$('#<?php echo $alias ?>').css("left","");
					$('html').removeClass('ves-navopen');
					setTimeout(function () {
						$('html').removeClass('ves-nav-before-open');
					}, 300);
					$(this).remove();
					return false;
				});

				$("#<?php echo $alias ?> .dynamic-items li").hover(function(){
					$(this).parents(".dynamic-items").find("li").removeClass("dynamic-active");
					$(this).addClass("dynamic-active");
					var id = $(this).data("dynamic-id");
					$("#<?php echo $alias ?> ."+id).parent().find(".dynamic-item").removeClass("dynamic-active");
					$("#<?php echo $alias ?> ."+id).addClass("dynamic-active");
				});
				var mImg = '';
				$("#<?php echo $alias ?> img").hover(function(){
					mImg = '';
					mImg = $(this).attr('src');
					if ($(this).data('hoverimg')){
						$(this).attr('src',$(this).data('hoverimg'));
					}
				},function(){
					$(this).attr('src',mImg);
				});
				$("#<?php echo $alias ?> li a").hover(function(){
					$(this).css({
						"background-color": $(this).data("hover-bgcolor"),
						"color": $(this).data("hover-color")
					});
				}, function(){
					$(this).css({
						"background-color": $(this).data("bgcolor"),
						"color": $(this).data("color")
					});
				});
				$(window).on("resize load", function(){
					if ($("#<?php echo $alias ?>").data("disable-bellow")){
						if ($(window).width() <= $("#<?php echo $alias ?>").data("disable-bellow")){
							$("#<?php echo $alias ?>-menu").hide();
						}else{
							$("#<?php echo $alias ?>-menu").show();
						}
					}
					$("#<?php echo $alias ?>").find("li").each(function(index, element){
						if ($(this).data("disable-bellow") && $(window).width() <= $(this).data("disable-bellow")){
							$(this).addClass("hidden");
						} else if ($(this).hasClass("hidden")){
							$(this).removeClass("hidden");
						}
					});
					if ($(window).width() >= 768 && $(window).width() <= 1024){
						$("#<?php echo $alias ?> .nav-anchor").off().click(function(){
							var iParent = $(this).parent('li');
							iParent.addClass("clicked");
							if ($(iParent).children('.submenu').length == 1){
								iParent.trigger('hover');
								if (iParent.hasClass('submenu-alignleft') || iParent.hasClass('submenu-alignright')){
									if ((iParent.offset().left + iParent.find('.submenu').eq(0).width()) > $(window).width()){
										iParent.find('.submenu').eq(0).css('max-width','100%');
										iParent.css('position','static');
									}
								}
								return false;
							}
						});
					}else{
						$("#<?php echo $alias ?>").find('.submenu').css('max-width','');
						$("#<?php echo $alias ?>").find('.submenu-alignleft').css('position','relative');
					}
					if ($(window).width() <= 768){
						$('.sections.nav-sections').removeAttr( "style" )
						$("#<?php echo $alias ?>").addClass("nav-mobile");
					}else{
						$("#<?php echo $alias ?>").find(".submenu").css({'display':''});
						$("#<?php echo $alias ?>").find("div").removeClass("mbactive");
						$("#<?php echo $alias ?>").removeClass("nav-mobile");
					}
				}).resize();
				//Toggle mobile menu
				$('.ves-megamenu-mobile #<?php echo $alias ?> .opener').on('click', function(e) {
					e.preventDefault();
					$("#<?php echo $alias ?> .nav-item").removeClass("item-active");
					var parent = $(this).parents(".nav-item").eq(0);
					$(this).toggleClass('item-active');
					$(parent).find(".submenu").eq(0).slideToggle();
					return false;
				});

			});
		</script>
		<?php } ?>
	</div>
	<?php } ?>
