<?php
if($menu = $this->getMenu()){
	$data = $this->helper("Ves\Megamenu\Helper\Data");
	$html = $drilldown=$class = '';
	$mobileTemplate = $menu->getData("mobile_template");
	if($this->hasData("mobile_template")) $mobileTemplate = $this->getData("mobile_template");
	if($mobileTemplate == 0 || $mobileTemplate == 2){
		$class = 'offcanvas-menu offcanvas-menu-left';
	}elseif($mobileTemplate == 1){
		$class = 'accordion-menu';
	}elseif($mobileTemplate == 3) {
		$class = 'drill-down-menu visually-hidden';
		$drilldown = 'ves-drill-down';
	}
	if($mobileTemplate == 2 && $menu->getMobileMenuAlias() && $this->getMobileDetect()->isMobile()){
		$html = $block->getMobileTemplateHtml($menu->getMobileMenuAlias());
	} else {
		$menuItems = $menu->getData('menuItems');
		$structure = json_decode($menu->getStructure(), true);
		if(is_array($structure)){
			foreach ($structure as $k => $v) {
				$itemData = $data->renderMenuItemData($v, [], $menuItems);
				$html .= $data->drawItem($itemData);
			}
		}
	}
	if($mobileTemplate == 3) {
		$nav = 'navdrilldown';
	}else{
		$nav = 'navigation';
	}
	$html = $data->filter($html);
	$alias = $menu->getAlias().time().rand();
	$disableBellow = (int)$menu->getData('disable_bellow');

	
	$disableItemBlocks = $menu->getData("disable_iblocks");
	if($disableItemBlocks)
		$class .= ' hide-blocks';

	$event = $menu->getData("event");
	if(!$event) $event = 'hover';
	$id = time().rand();

	$desktopTemplate = $menu->getData("desktop_template");
	if(!$desktopTemplate) $desktopTemplate = 'horizontal';
	if($this->hasData("desktop_template")) $desktopTemplate = $this->getData("desktop_template");
	if($desktopTemplate == 'vertical-left' ||  $desktopTemplate == 'vertical-right'){
		$class .= ' ves-vertical';
	}
	?>
	<div class="block ves-menu mgm-widget <?php echo $menu->getData("classes").' '.$drilldown; ?>" id="<?php echo $alias ?>-menu">
		<?php if($title = $this->getData("title")){ ?>
		<div class="block-title"><strong><span><?php echo __($title); ?></span></strong></div>
		<?php } ?>
		<?php // Off Canvas Menu ?>
		<?php if($mobileTemplate == 0 || $mobileTemplate == 2){ ?>
		<div class="navbar ves-navbar">
			<span class="ves-navtoggle ves-navtoggle<?php echo $id ?>">
				<span><?php echo __('Toggle Nav'); ?></span>
			</span>
		</div>
		<?php } elseif($mobileTemplate == 3) { ?>
		<div class="navbar ves-navbar">
			<div class="ves-navdrilldown ves-navdrilldown<?php echo $id ?>">
				<span><?php echo __('Toggle Nav'); ?></span>
			</div>
		</div>	
		<?php } ?>	
		<div class="<?php echo $nav; ?>">
			<ul id="<?php echo $alias ?>" class="ves-megamenu <?php echo 'menu-' . $event; ?> <?php echo $class; ?> ves-<?php echo $desktopTemplate ?>" <?php if($disableBellow>0){ ?>data-disable-bellow="<?php echo $disableBellow ?>"<?php } ?>>
				<?php echo $html; ?>
			</ul>
		</div>
		<?php if($html!=''){ ?>
		<script type="text/javascript">
			require([
				'jquery',
				<?php if($menu->getData('scrolltofixed')){ ?>'scrolltofixed'<?php } ?>
				],function($){
					jQuery(document).ready(function($) {
						<?php if($desktopTemplate == 'horizontal'){ ?>
							jQuery('#<?php echo $alias ?>-menu .ves-megamenu .level0').hover(function() {
								if ($(window).width() >= 768){
									var mParent = jQuery(this).parents('.ves-megamenu').offset().top;
									var mHeight = jQuery(this).offset().top;
									var mTop    = (mHeight - mParent) + jQuery(this).height();
									jQuery(this).find('.submenu').first().css({top:mTop+"px"});
								}
							});
							<?php } ?>
							<?php if($mobileTemplate == 3) { ?>

								$('.drill-down-menu').find('.opener').addClass('ves-click');
								
								var toggle      = $('.ves-navdrilldown');
								var nav 		= $('.ves-menu');
								var menu        = $('.drill-down-menu'); 
								var back        = '<div class="hide-submenu"></div>';
								var subHide     = $(back);
								var subMenu       = $('.drill-down-menu .submenu');
								// Add submenu hide bar
								subHide.prependTo(subMenu);
								var subHideToggle = $('.drill-down-menu .hide-submenu');
								// Toggle menu
								toggle.on("click", function() {
									nav.toggleClass('is-visible');
									if(menu.hasClass('visually-hidden')) {
										menu.toggleClass('visually-hidden is-visible')
									} else {
										menu.removeClass('is-visible');
									    // Wait for CSS animation
									    setTimeout(function() {
									    	nav.removeClass('view-submenu');
									    	menu.addClass('visually-hidden');
									    }, 200);
									}
								});
								// Hide submenu
								subHideToggle.on("click", function() {
								  	//nav.removeClass('view-submenu');
								  	$(this).parent().parent().parent().removeClass('view-submenu');
								  	$(this).parent().parent().parent().parent().parent().parent().parent().parent().removeClass('view-submenu');
								  	$(this).parent().hide();
								  });
								

								
								$(window).resize(function(e){
									e.preventDefault();
									if ($(window).width() <= 768){
										$('.navdrilldown').addClass('mobile').removeClass('desktop');
										$('.drill-down-menu').find('.submenu').css('display','none');
										$('.navbar.ves-navbar').css('margin-bottom','0');
										//$('.mgm-widget .navigation').addClass('navdrilldown').removeClass('navigation');
										$('.drill-down-menu').find('.opener').removeClass('item-active');
										$('.drill-down-menu').find('.opener').addClass('fa fa-arrow-right').removeClass('opener');
										
										$('.navdrilldown.mobile #<?php echo $alias ?>.drill-down-menu .ves-click').on('click', function(e) {
											e.preventDefault();
											if ($(window).width() <= 768){	
												$(this).removeClass('.item-active');
												$(this).parents('.submenu').addClass('view-submenu');
												$(this).parents('ul.drill-down-menu').addClass('view-submenu');
												
												var a = $(this).parents('li.nav-item').offset().top;
												var b = $(this).parents('ul.drill-down-menu').offset().top;
												var c = $(this).parent().parent().offset().top;

												$(this).parents('li.nav-item').children('.submenu').css('top',b-a+'px');
												$(this).parent().parent().children('.submenu').css('top',b-c+'px');
												$('.submenu.dropdown-menu').hide();
												// ...except for the one being called
												$(this).parents('.submenu').show();
												$(this).parent().parent().children('.submenu').show();

												return false;
											}	
										});
									}else{
										$('.navdrilldown').addClass('desktop').removeClass('mobile');
										$('.drill-down-menu').find('.fa-arrow-right').addClass('opener').removeClass('fa fa-arrow-right');
										//$('.drill-down-menu').css('transform','none');
										
										//$('.navdrilldown').addClass('navigation').removeClass('navdrilldown');
										
									}
								});
								//Toggle mobile menu
								$('.navdrilldown #<?php echo $alias ?> .opener').on('click', function(e) {
									e.preventDefault();
									$(".navdrilldown #<?php echo $alias ?> .nav-item").removeClass("item-active");
									var parent = $(this).parents(".nav-item").eq(0);
									$(this).toggleClass('item-active');
									$(parent).find(".submenu").eq(0).slideToggle();
									return false;
									
								});
								<?php } ?>	
								<?php if($menu->getData('scrolltofixed')){ ?>
									$('#<?php echo $alias ?>').scrollToFixed({
										zIndex: 99
									});
									$(window).on("resize load", function(){
										if ($(window).width() < 768){
											$('#<?php echo $alias ?>').css({position: '', top: '', width: '100%'});
										}
									});
									var menuParentPosition<?php echo $id ?> = $('#<?php echo $alias ?>').parent().offset().top;
									$(window).scroll(function() {
										var height = $(window).scrollTop();
										console.log(height);
										if (height<(menuParentPosition<?php echo $id ?>) - $('#<?php echo $alias ?>-menu').height()) {
											$('#<?php echo $alias ?>').css({position: '', top: '', width: '100%'});
										}
									});
									<?php } ?>
									$("#<?php echo $alias ?> .dynamic-items li:first").addClass("dynamic-active");
									var id = $("#<?php echo $alias ?> .dynamic-items li:first").data("dynamic-id");
									$("#<?php echo $alias ?> ."+id).addClass("dynamic-active");
									$("#<?php echo $alias ?> .level0 .submenu").find(".active").addClass("");
									$("#<?php echo $alias ?>").find(".level0 .submenu").each(function(index, elemetn){
										var eSelected = $(this).find(".active");
										if(eSelected.length){
											$(this).addClass("active");
										}
									});
									$('#<?php echo $alias ?> p').each(function() {
										var $this = $(this);
										if($this.html().replace(/\s|&nbsp;/g, '').length == 0)
										$this.remove();
									});
									$("#<?php echo $alias ?> .dynamic-items li").hover(function(){
										$(this).parents(".dynamic-items").find("li").removeClass("dynamic-active");
										$(this).addClass("dynamic-active");
										var id = $(this).data("dynamic-id");
										$("#<?php echo $alias ?> ."+id).parent().find(".dynamic-item").removeClass("dynamic-active");
										$("#<?php echo $alias ?> ."+id).addClass("dynamic-active");
									});
									var ihBgcolor, ihColor, ibgColor, icolor;
									$("#<?php echo $alias ?> .nav-item > a").hover(function(){
										ihBgcolor = ihColor = ibgColor = icolor = '';
										ihBgcolor = $(this).data("hover-bgcolor");
										ihColor   = $(this).data("hover-color");
										ibgColor  = $(this).data("bgcolor");
										icolor    = $(this).data("color");
										$(this).css({
											"background-color": ihBgcolor,
											"color": ihColor
										});
									}, function(){
										if(typeof(ibgColor)=='undefined'){
											ibgColor = '';
										}
										if(typeof(icolor)=='undefined'){
											icolor = '';
										}
										$(this).css({
											"background-color": ibgColor,
											"color": icolor
										});
									});
									var mImg = '';
									$("#<?php echo $alias ?> img").hover(function(){
										mImg = '';
										mImg = $(this).attr('src');
										if($(this).data('hoverimg')){
											$(this).attr('src',$(this).data('hoverimg'));
										}
									},function(){
										$(this).attr('src',mImg);
									});
									$("#<?php echo $alias ?> li a").hover(function(){
										$(this).css({
											"background-color": $(this).data("hover-bgcolor"),
											"color": $(this).data("hover-color")
										});
									}, function(){
										$(this).css({
											"background-color": $(this).data("bgcolor"),
											"color": $(this).data("color")
										});
									});
									$(window).on("resize load", function(){
										if($("#<?php echo $alias ?>").data("disable-bellow")){
											if ($(window).width() <= $("#<?php echo $alias ?>").data("disable-bellow")){
												$("#<?php echo $alias ?>").hide();
											}else{
												$("#<?php echo $alias ?>").show();
											}
										}
										if ($(window).width() >= 768 && $(window).width() <= 1024){
											$("#<?php echo $alias ?> .nav-anchor").off().click(function(){
												var iParent = $(this).parent('li');
												iParent.addClass("clicked");
												if($(iParent).children('.submenu').length == 1){
													iParent.trigger('hover');
													if(iParent.hasClass('submenu-alignleft') || iParent.hasClass('submenu-alignright')){
														if((iParent.offset().left + iParent.find('.submenu').eq(0).width()) > $(window).width()){
															iParent.find('.submenu').eq(0).css('max-width','100%');
															iParent.css('position','static');
														}
													}
													return false;
												}
											});
										}else{
											$("#<?php echo $alias ?>").find('.submenu').css('max-width','');
											$("#<?php echo $alias ?>").find('.submenu-alignleft').css('position','relative');
										}
										$("#<?php echo $alias ?>").find("li").each(function(index, element){
											if($(this).data("disable-bellow") && $(window).width() <= $(this).data("disable-bellow")){
												$(this).addClass("hidden");
											}else if($(this).hasClass("hidden")){
												$(this).removeClass("hidden");
											}
										});
										if ($(window).width() <= 768){
											$("#<?php echo $alias ?>").addClass("nav-mobile");
										}else{
											$("#<?php echo $alias ?>").find(".submenu").css({'display':''});
											$("#<?php echo $alias ?>").find("div").removeClass("mbactive");
											$("#<?php echo $alias ?>").removeClass("nav-mobile");
										}
									}).resize();
								//Toggle mobile menu
								$('.navigation #<?php echo $alias ?> .opener').on('click', function(e) {
									e.preventDefault();
									$("#<?php echo $alias ?> .nav-item").removeClass("item-active");
									var parent = $(this).parents(".nav-item").eq(0);
									$(this).toggleClass('item-active');
									$(parent).find(".submenu").eq(0).slideToggle();
									return false;
								});
								$("#<?php echo $alias ?>-menu .ves-navtoggle<?php echo $id ?>").click(function(){
									jQuery("html, body").animate({ scrollTop: 1000 }, 600);
									$('html').removeClass('nav-before-open nav-open');
									$('.ves-overlay<?php echo $alias ?>').show();
									$("#<?php echo $alias ?>-menu").append('<div class="ves-overlay ves-overlay<?php echo $alias ?>"></div>');
									$('#<?php echo $alias ?>').css("left", "0px");
									if ($('html').hasClass('ves-navopen')) {
										$('html').removeClass('ves-navopen');
										setTimeout(function () {
											$('html').removeClass('ves-nav-before-open');
										}, 300);
									}	 else {
										$('html').addClass('ves-nav-before-open');
										setTimeout(function () {
											$('html').addClass('ves-navopen');
										}, 42);
									}
								});
								$(document).on("click", ".ves-overlay<?php echo $alias ?>", function(){
									$('#<?php echo $alias ?>').css("left","");
									$('html').removeClass('ves-navopen');
									setTimeout(function () {
										$('html').removeClass('ves-nav-before-open');
									}, 300);
									$(this).remove();
									return false;
								});

							});
});
</script>
<?php } ?>
</div>
<?php } ?>
