<?php $helper = $this->helper('\Magento\Catalog\Helper\Data'); ?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <?php
            $checked = '';
            $plus = '';
            $countStyle = 'swissup-count-green';
            if(!$filterItem->getActive()) {
                $url = $filterItem->getUrl();
            } else {
                $checked = 'checked';
                $url = $filterItem->getRemoveUrl();
            }
            if($filterItem->getPlus()) {
                $plus = '+';
                $countStyle = 'swissup-count-red';
            }
        ?>
        <li class="item">
            <div class="swissup-filter-item-checkbox">
                <input type="checkbox" class="swissup-layered-checkbox" <?php echo $checked ?>>
                <div class="swissup-content"></div>
            </div>
            <a class="swissup-aln-item" href="<?php echo $block->escapeUrl($url) ?>">
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if (!$filterItem->getActive() && $filterItem->getCount() > 0): ?>
                    <span class="count swissup-option-count <?php echo $countStyle ?>">
                    <?php /* @escapeNotVerified */ echo $plus . $filterItem->getCount() ?></span>
                <?php endif; ?>
            </a>
        </li>
    <?php endforeach ?>
</ol>
