<?php
    $configHelper = $this->helper('Swissup\Ajaxlayerednavigation\Helper\Config');
    $jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
    $pricePos = $configHelper->getPriceCurrencyPos();
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	
?>
<script type="text/x-magento-init">
{
    "*": {
        "AjaxLayeredNavigation": <?php /* @escapeNotVerified */ echo $jsonHelper->jsonEncode([
            'useAjax' => (bool)$configHelper->iaAjaxEnable(),
            'pricePrefix' => $pricePos['prefix'],
            'pricePostfix' => $pricePos['postfix'],
			'baseurl' => $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK)
        ]) ?>
    }
}
</script>