<?php $helper = $block->helper;?>
<div class="admin__field order-create-field">
    <label class="label admin__field-label">
        <span>Delivery Date</span>
    </label>
    <input
        type="text"
        id="delivery-date"
        name="delivery-date"
        class="admin__control-text"
        value=""
        >
</div>

<script>
    require([
        'jquery',
        'uiRegistry'
    ], function($, registry){
        $(function (){
            var deliveryDate = $('#delivery-date');
            var defaultDate = new Date(<?php echo $block->getStoredDeliveryDate(); ?>);
            var options = {
                minDate : <?php echo $helper->getMinDelayDays(); ?>,
                maxDate : <?php echo $helper->getMaxDelayDays(); ?>,
                dateFormat: "<?php echo $helper->getDateFormat(); ?>",
                // beforeShowDay : beforeShowDay,
                defaultDate : defaultDate
            };

            $(deliveryDate).datepicker(options);
            $(deliveryDate).datepicker('setDate', options.defaultDate);

            $(deliveryDate).on('change', function(event) {
                order.loadArea(
                    ['shipping_method'],
                    true,
                    {delivery_date : $('#delivery-date').val()}
                );
            });
        });
    });
</script>
